import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Keyboard from "../../components/keyboard";
import App from "../../components/UIElements/key";
import Synth from "../../classes/Synth";
import { useState, useEffect, useRef } from "react";
import Player from "../../classes/Player";
const inter = Inter({ subsets: ["latin"] });
import { useAudioContext } from "../../providers/AudioContextContext";

const testTrack = {
  notes: [
    "C-3",
    "D#3",
    "G-3",
    "C-3",
    "D-3",
    "D#3",
    "C-3",
    "D-3",
    "D#3",
    "C-3",
    "D#3",
    "G#3",
    "C-3",
    "G-3",
    "C-3",
    "G-3",
  ],
  type: "synth",
  params: [],
  effects: [{ type: "delay", val: "lots" }],
};

export default function Home() {
  const [tracks, setTracks] = useState([]);
  const [actx, setActx] = useState(null);
  const [showKeyboard, setShowKeyboard] = useState(true);

  let player = new Player(useAudioContext());
  //   const initializeSynth = () => {
  //     const AC = new AudioContext();
  //     setActx(AC);
  //     if (!player) {
  //       player = new Player(AC);
  //     }
  //   };
  //   useEffect(() => {
  //     initializeSynth();
  //   }, []);

  //   const show = () => {
  //     setShowKeyboard(true);
  //   };

  const seqCallback = (stepIndex) => {
    console.log("seqCallback", stepIndex);
    dispatch(ActionCreators.setPlayingStep(stepIndex));
  };
  const renderKeyboard = () => {
    return <Keyboard />;
  };

  const startSequencer = () => {
    player.isPlaying ? player.stop() : player.play(seqCallback);
  };
  const handlePlay = () => {
    //play
    startSequencer();
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <button onClick={handlePlay}>Play All</button>

        <Keyboard />
      </main>
    </>
  );
}
